實作離開房間
Game-as-a-Service/Lobby-Platform-Service pull request #101
Opened 2023-06-22 04:08 UTC by ted791029

## Why need this change? / Root cause: 
- A user want to leave room
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #30

2023-06-22 14:19 UTC, frankvicky requested changes

2023-06-22 14:19 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    fun getFirstPlayer(): Player? = players[0]
`players.first()`

2023-06-22 14:19 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +        return host.matchesId(player);
`fun isHost(player: Player): Boolean = host.matchesId(player)`
不需要分號。

2023-06-22 14:19 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +        }
Q：這個方法是必要的嗎？

2023-06-22 15:10 UTC, Wally5077 requested changes
Review done.

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenLeaveRoomSuccessfully()
`thenPlayerShouldNotInRoom(playerB, roomD)`

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        givenHostAndUsersAreInTheRoom(host, players)
`givenHostAndPlayersAreInTheRoom(host, players)`

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
上方測試案例直接讓 host 離開房間就都能測到了

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
不存在房間的玩家離開房間，就當他是正常離開房間，所以這個測試案例可以移除

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
ditto 這個可以不需要了

2023-06-22 15:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
這邊還要再驗證，玩家是不是真的從房間離開了，所以你需要從資料庫驗證

2023-06-24 11:55 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(User::class).id(userId.value)
已修正

2023-06-24 11:55 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(Room::class).id(roomId)
已修正

2023-06-24 11:55 UTC, ted791029 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +        return host.matchesId(player);
已修正

2023-06-24 11:56 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(Room::class).id(roomId)
已修正

2023-07-04 01:49 UTC, Wally5077 requested changes
**Review done.**

2023-07-04 01:49 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +
這邊空到兩行了，空一行就好

2023-07-04 01:49 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    fun changeHost() {
如果這個 fun 不會給其他類別用，就使用 private 
否則，任何類別都可以竄改 Host 了

2023-07-04 01:49 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenHostAndPlayersAreInRoom_WhenPlayerLeaveRoom_ThenThisPlayerShouldNotInRoom() {
`givenHostAndPlayerBAndPlayerCAreInRoom_WhenPlayerBLeaveRoom_ThenPlayerBShouldBeNotInRoom`
命名要具體一點

2023-07-04 01:49 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenThisPlayerShouldNotInRoom(host, roomRepository.findById(roomD.roomId!!)!!)
1. userB 直接 toRoomPlayer，並用 playerB 命名就好，不太需要多次 userB.toRoomPlayer()
2. 第二個參數給 roomD 物件進去就好
3. 直接讓 host 離開房間，就能連換 host 也測試到了
4. `thenPlayerShouldBeNotInRoom` 即可，不用加 this 特別指明「這個玩家」

2023-07-04 01:49 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun givenHostAndPlayersAreInTheRoom(host: Player, players: MutableList<Player>): Room {
players 改用 varargs，外面調用會比較便利

2023-07-05 15:21 UTC, Wally5077 requested changes
**Review done.**

2023-07-05 15:21 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
這不需要，如果需要不存在的房間，就給不存在的 Room.Id 就好了

2023-07-05 15:21 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        val userC = createUser("3", "test3@mail.com", "winner0033")
不需要宣告userB 和 userC，直接是 playerB 和 playerC 就好了

2023-07-05 15:21 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenHostAndPlayerBAndPlayerCAreInRoomD_WhenPlayerALeaveRoomD_ThenPlayerAShouldBeNotInRoomDAndHostIsChanged() {
`givenHostAndPlayerBAndPlayerCAreInRoomD_WhenHostLeaveRoomD_ThenPreviousHostShouldBeNotInRoomDAndChangedNewHost`

2023-07-05 15:21 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        val roomD = givenHostAndPlayersAreInTheRoom(host, host, playerB, playerC)
`val roomD = givenHostAndPlayersAreInTheRoom(host, playerB, playerC)`
如果你需要玩家列表有 host，就在 `givenHostAndPlayersAreInTheRoom` 自己加入就好了

2023-07-05 16:20 UTC, Wally5077 requested changes
**Review done.**

2023-07-05 16:20 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenPlayerShouldBeNotInRoomAndHostIsChanged(host)
281 和 282 中間空行
```java
givenHostAndPlayersAreInTheRoom(host, playerB, playerC)
.whenUserLeaveTheRoom(userA)
.thenPlayerShouldBeNotInRoomAndHostIsChanged(host)
```

2023-07-06 03:48 UTC, Wally5077 approved these changes
**LGTM**

2023-07-06 04:10 UTC, frankvicky approved these changes

2023-07-08 04:19 UTC, merged