關閉房間
Game-as-a-Service/Lobby-Platform-Service pull request #102
Opened 2023-06-25 10:11 UTC by mikaeloduh

## Why need this change? / Root cause: 

- 關閉房間

## Changes made:

- add closeRoom API

## Test Scope / Change impact:

- `CloseRoomUsecase` and  `closeRoom`

## Issue

- https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/29

2023-06-25 10:52 UTC, frankvicky requested changes

2023-06-25 10:52 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(Room::class).id(roomId)
`NotFoundException` static import

2023-06-25 10:52 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +            throw PlatformException("not a host")
不要省略大括號

2023-06-25 10:54 UTC, frankvicky requested changes

2023-06-25 10:54 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_RoomOwnerCloseRoom_ShouldSuccess() {
RoomOwner？
不是 host 嗎？

2023-06-25 11:01 UTC, Wally5077 requested changes
**Review done.**

2023-06-25 11:01 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_NonRoomOwnerCloseRoom_ShouldFail() {
**givenHostCreatedRoom_whenNonHostPlayerCloseRoom_ShouldFail**

2023-06-25 11:01 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(Room::class).id(roomId)
修正在 43bd913acc9242846f6e62f638ccac30ece437b5

2023-06-25 11:01 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +            throw PlatformException("not a host")
修正在 43bd913acc9242846f6e62f638ccac30ece437b5

2023-06-25 11:02 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_RoomOwnerCloseRoom_ShouldSuccess() {
修正在 d3c3275a904eb3306a82baec9ff451d40963cb76

2023-06-25 11:12 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +        room.deleteRoom()
修正在 a2538c3fd4b658605eefb024fc7657e330d9761c

2023-06-25 11:13 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +    )
修正在 5bb42ad5b52495ffaf6274b755bf9da5de244650

2023-06-25 11:13 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +            throw PlatformException("not a host")
修正在 913dcc470efba3360148279cda63481d87efb630

2023-06-25 11:13 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CloseRoomUsecase.kt
> +        room.deleteRoom()
修正在 55cb6bcb0f237dd79ed6acb676a7c182343cb6b2

2023-06-25 11:14 UTC, mikaeloduh commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        @AuthenticationPrincipal principal: OidcUser,
不太清楚怎麼用，有沒有範例？

2023-06-25 11:14 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_RoomOwnerCloseRoom_ShouldSuccess() {
> 修正在 [d3c3275](https://github.com/Game-as-a-Service/Lobby-Platform-Service/commit/d3c3275a904eb3306a82baec9ff451d40963cb76)

Host 就好，Room 不用

2023-06-25 11:17 UTC, mikaeloduh commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
```kotlin
closeRoomsUseCase.execute(CloseRoomUsecase.Request(
            roomId = roomId,
            userId = joinerId,
        ))
```

這樣嗎？

2023-06-25 11:40 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_RoomOwnerCloseRoom_ShouldSuccess() {
修正在 18b1f045057e09cc460465330959d740f894c95a

2023-06-25 11:40 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenExistingRoom_NonRoomOwnerCloseRoom_ShouldFail() {
修正在 18b1f045057e09cc460465330959d740f894c95a

2023-06-25 11:42 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        ).andExpect(status().isNoContent)
抽成 function 嗎？感覺重複不多說

2023-06-25 11:56 UTC, Wally5077 requested changes
**Review done.**

2023-06-25 11:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        ).andExpect(status().isNoContent)
需要

2023-06-25 11:56 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
是，但不要直接放進 execute 裡，宣告一個 request 變數

2023-07-02 15:00 UTC, mikaeloduh commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
修正在 d23e599b5375fcd81fb2efa68defdcf7e296053a

2023-07-02 15:01 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        ).andExpect(status().isNoContent)
修正在 9f9293d039cd390853a61b09123ea269eaecb9b7

2023-07-02 15:01 UTC, mikaeloduh commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        @AuthenticationPrincipal principal: OidcUser,
修正在 3b7988f04fd43cdfe9bccb661a99796b0f0a534f

2023-07-02 15:34 UTC, Wally5077 approved these changes
**LGTM**

2023-07-03 03:03 UTC, frankvicky approved these changes

2023-07-03 06:45 UTC, merged