feature: room player readay and cancel
Game-as-a-Service/Lobby-Platform-Service pull request #105
Opened 2023-06-28 16:00 UTC by kuoche1712003

## Why need this change? / Root cause: 
- As a user in the room, I want to ready or cancel ready.
## Changes made:
- Room Player add readiness field.
- Refactor RoomRepository's joinRoom function name to update for reuse.
- Refactor JoinRoomViewModel name to RoomActionViewModel for reuse.
- Add ReadyForRoomUsecase and CancelReadyForRoomUsecase for feature.
## Test Scope / Change impact:
- RoomController
## Issue
- resolves https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/103, https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/104

2023-06-30 08:42 UTC, Wally5077 requested changes
**Review done.**

2023-06-30 08:50 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
我如果要客製化 NotFoundException API 回傳的內容
目前的統一例外處理好像做不到
我收到的 sepc 
```
Response 404
{
    "message": "Room not found"
}
```

2023-06-30 09:00 UTC, kuoche1712003 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    }
你的意思是指 readiness 改成 var 直接更改就可以了嗎？
```
class Player(
        val id: Id,
        val nickname: String,
        var readiness: Boolean = false
    ) {
        @JvmInline
        value class Id(val value: String)
    }
```
這樣表示 usecase 可以 getPlayer 不經由 Room 控管下改變 Player 的狀態嗎？

2023-06-30 13:59 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    }
使用 private set，增加 ready() 和 cancelReady()

2023-06-30 14:04 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
你可以調整 `NotFoundException`

2023-06-30 16:02 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
那我會連帶需要調整整個 RestControllerAdvice 的 response
原本只有回傳 string , 我直接改成我需要的 json 格式這樣 OK 嗎？
```
@RestControllerAdvice
class PlatformExceptionHandler {
    @ResponseStatus(NOT_FOUND)
    @ExceptionHandler(NotFoundException::class)
    fun notFound(exception: NotFoundException): String = exception.message!!

    @ResponseStatus(BAD_REQUEST)
    @ExceptionHandler(PlatformException::class)
    fun badRequest(exception: PlatformException): Map<String, String> = mapOf("message" to (exception.message ?: ""))
}
```

2023-06-30 16:31 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
我個人會覺得現在的 NotFoundException 封裝有他的邏輯在
如果我為了 API 要客製化 response body 而去修改它破壞他的封裝有點可惜
我認為在 controller catch 自行處理應該是最好的作法

不然就是要和前後端的人講清楚
這個錯誤會有統一的 response body 和 status code
不接受各 API 自己亂定

2023-07-01 06:26 UTC, frankvicky requested changes

2023-07-01 06:26 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
>      )
`private` 是為了保證大家都使用 builder 建立 `NotFoundException`，所以不建議拔掉

2023-07-01 06:50 UTC, Wally5077 requested changes
**Review done.**

2023-07-01 06:50 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    private fun targetPlayer(playerId: Player.Id): Player? = players.find { it.id == playerId }
`findPlayer(playerId)`

2023-07-01 06:50 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +        targetPlayer.readiness = readiness
Player 的 readiness 不能直接改，不然就直接暴露封裝了

2023-07-01 06:50 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +class NotFoundException constructor(message: String) : PlatformException(message) {
改這段顯示訊息就好了，不要讓建構子公開
![image](https://github.com/Game-as-a-Service/Lobby-Platform-Service/assets/26381900/b70fda02-1eca-4959-822f-ab20da0adbea)

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/aspects/PlatformExceptionHandler.kt
> +    fun notFound(exception: NotFoundException): Map<String, String> = mapOf("message" to exception.message!!)
不要這麼做，如果你需要統一的模組，應該開一個 PlatformViewModel 類別，而不是採用 Map
另外，RoomActionViewModel 改成用 PlatformViewModel

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +            ChangePlayerReadinessUsecase.Request(roomId, jwt.subject, true)
1. `ChangePlayerReadinessUsecase.Request.ready(roomId, jwt.subject)`
2. request 宣告下變數

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +            ChangePlayerReadinessUsecase.Request(roomId, jwt.subject, false)
1. `ChangePlayerReadinessUsecase.Request.cancelReady(roomId, jwt.subject)`
2. request 宣告下變數

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
抽出去成另一個類別

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/RoomData.kt
> +        var readiness: Boolean
加上 nickName

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +        val nicknameMap = userRepository.findAllById(playerIds)
`idToNickname`

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .whenUserReadyFor(roomAId)
1. `whenUserGetReadyFor(roomA, userA)`
2. `userA.id!!.value.toJwt()` 在外面看起來很怪

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        val roomAId = createRoom(userA).roomId!!
取 room 本身

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        assertRoomPlayerReadinessEqual(roomAId, userA, true)
直接 `assertRoomPlayerGetReady`，比 boolean flag 更讓人明確知道這在驗證什麼

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        assertRoomPlayerReadinessEqual(roomAId, userA, false)
ditto 驗證方法命名不夠明確

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenActionFailedWithCodeAndMessage(404, "Room not found")
我想你可以考慮使用 `thenShouldBeNotFound(Room.class)`

2023-07-01 06:50 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenActionFailedWithMessage("Player not joined")
`thenShouldFail("Player not joined")`

2023-07-01 07:51 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/RoomData.kt
> +        var readiness: Boolean
@Wally5077 這個是表示要直接 embedded 進去
之後查詢就不用額外查 User 嗎？

2023-07-01 09:53 UTC, Wally5077 requested changes
**Review done.**

2023-07-01 09:53 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +            fun message(message: String): NotFoundException = NotFoundException(message)
`NotFoundException("$resourceName not found.")`

2023-07-01 09:53 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            players = players.map { it.toDomain() }.toMutableList(),
Q：map 出來的時候，如果是 mutableList，就不要 toMutableList 了

2023-07-01 09:53 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        assertRoomPlayerUnready(roomA, userA)
`assertRoomPlayerNotReady`

2023-07-01 14:54 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            players = players.map { it.toDomain() }.toMutableList(),
map 出來是 List

2023-07-01 15:56 UTC, Wally5077 requested changes
**Review done.**

2023-07-01 15:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .andExpect(jsonPath("$.message").value(notFound(resourceType).shortMessage().message))
`value(notFound("${resourceType.simpleName!!} not found")`

2023-07-01 15:56 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/RoomData.kt
> +        var readiness: Boolean
val

2023-07-01 15:56 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +    )
可以不用這個

2023-07-01 15:56 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +            fun shortMessage(): NotFoundException = NotFoundException("${resourceName.capitalize()} not found")
這也可以刪掉

2023-07-02 05:32 UTC, Wally5077 approved these changes
**LGTM**

2023-07-02 05:36 UTC, frankvicky approved these changes

2023-07-02 05:37 UTC, merged