feature: PUT /users/me
Game-as-a-Service/Lobby-Platform-Service pull request #109
Opened 2023-07-02 11:26 UTC by lohas1107

## Why need this change? / Root cause: 
- As a user, I want update my nickname
## Changes made:
- User related
## Test Scope / Change impact:
- UserController
## Issue
- resolve #25

2023-07-07 12:42 UTC, frankvicky requested changes

2023-07-07 12:43 UTC, frankvicky requested changes

2023-07-07 12:43 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +    }
Q：為什麼需要先轉換成 `ByteArray`

2023-07-07 13:03 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +    override fun existsUserByNickname(nickname: String): Boolean =
不要黏再一起

2023-07-07 13:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +    private fun generateJwt(email: String, subject: String): Jwt =
1. subject 和 email 對調一下
2. subject 改叫 id

2023-07-07 13:18 UTC, lohas1107 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +    }
因為中英文的長度限制不一樣：
最少 4 英文字元 (= 2 中文字)
最長 16 英文字元 (= 8 中文字)

這邊用 byte 計算長度就不用判斷是哪種文字

2023-07-07 14:50 UTC, lohas1107 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +        }
1
因為之前的結論是限制字元長度，所以這邊先轉成字元再判斷長度
最少 4 英文字元 (= 2 中文字)
最長 16 英文字元 (= 8 中文字)

2 & 3 已調整

2023-07-07 14:50 UTC, lohas1107 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +            val updatedUser = user.updateNickname(request.nickname)
已調整

2023-07-07 14:50 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +    }
已調整

2023-07-07 14:50 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +    fun toRequest(principal: Jwt): UpdateUserUseCase.Request {
已調整

2023-07-07 14:50 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/presenter/UpdateUserPresenter.kt
> +    fun getViewModel(): UpdateUserViewModel = viewModel
已調整

2023-07-07 14:50 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +    override fun existsUserByNickname(nickname: String): Boolean =
已調整

2023-07-07 14:50 UTC, lohas1107 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +    private fun generateJwt(email: String, subject: String): Jwt =
已調整

2023-07-07 15:20 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +    }
那可以把 `nickname.toByteArray()` 宣告成變數 🐣

2023-07-07 15:55 UTC, frankvicky requested changes

2023-07-07 15:55 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +    private val nicknameByteSizeMaximum: Int = 16
```kotlin
companion object {
    private const val NICK_NAME_MINIMUM_BYTE_SIZE = 4
    private const val NICK_NAME_MAXIMUM_BYTE_SIZE = 16
} 
```

2023-07-07 15:55 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +        if (nickname.toByteArray().size < nicknameByteSizeMinimum) {
`nickname.toByteArray()` 用變數接

2023-07-07 15:55 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +    }
```kotlin
private val Jwt.email: String
    get() = claims["email"]?.let { it as String }
        ?: throw PlatformException("JWT email should exist.")
```

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    }
1. 這個測試案例可以改成這樣：
```kotlin
fun givenUserNamedNeverever_whenChangeUserNicknameToAbc_thenUserNickNameShouldBeAbc() {
    givenUserNickname("Neverever")
        .whenChangeUserNickName(UpdateUserRequest("abc"))
        .thenShouldUpdateNickname("abc")
}
```
2. 下面的測試案例名稱可以依照上方範例檢視然後修改

2023-07-07 15:55 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +    fun updateNickname(nickname: String) {
`fun changeNickname(nickname: String)`

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    }
在存進資料庫前不會有任何 UserId 存在

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +        val user = User(User.Id("2"), "userB@example.com", "周杰倫", mockUser.identities)
ditto，在存進資料庫前不會有任何 UserId 存在

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +            .also { assertThat(it.message).contains(message) }
1. 應該可以用 `jsonPath` 比對
2. 將 `exists()` 改為 `value()` 就可以比對了

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    private fun ResultActions.thenShouldUpdateNicknameFailed(message: String) {
`thenShouldChangeNicknameFailed`

2023-07-07 15:55 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    private fun ResultActions.thenShouldUpdateNickname(nickname: String) {
`thenUserNickNameSholdBeChanged`

2023-07-08 06:30 UTC, Wally5077 requested changes
**Review done.**

2023-07-08 06:30 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +    get() = claims["email"]?.let { it as String }
這能變成下方這樣嗎？
```kotlin
claims["email"] ?as String ?: throw PlatformException("JWT email should exist.")
```

2023-07-08 06:30 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +        val user = User(null, "userA@example.com", nickname, mockUser.identities)
覆寫一個不用 UserId 的 User 建構子，這邊不要直接給 Id null

2023-07-08 06:30 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +        val user = User(null, "userB@example.com", nickname, mockUser.identities)
ditto User 建構子

2023-07-08 06:30 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +        val userViewModel = andExpect(status().isOk)
`userViewModel` -> `user`

2023-07-08 06:30 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +
空一行就好

2023-07-08 12:36 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +    get() = claims["email"]?.let { it as String }
不能 `?as String`，但可以 `?.toString()`。

2023-07-08 12:39 UTC, Wally5077 approved these changes
**LGTM**

2023-07-08 16:16 UTC, frankvicky approved these changes

2023-07-09 00:43 UTC, merged