test: replace Oidc with JWT
Game-as-a-Service/Lobby-Platform-Service pull request #122
Opened 2023-07-11 07:31 UTC by mikaeloduh

## Why need this change? / Root cause: 
-
## Changes made:
-
## Test Scope / Change impact:
-
## Issue
-

2023-07-11 14:24 UTC, Wally5077 requested changes
**Review done.**

2023-07-11 14:24 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +                .with(jwt().jwt(mockUserJwt(joinUser)))
都改成 withJwt

2023-07-11 15:03 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +                .with(jwt().jwt(mockUserJwt(joinUser)))
修改在 bb05336d9491ee8ca0328a7565beaa56dec59336

2023-07-13 02:48 UTC, frankvicky approved these changes

2023-07-13 05:47 UTC, mikaeloduh commented
@Wally5077 @frankvicky 跟 main 的 conflict 解了

2023-07-16 11:39 UTC, Wally5077 requested changes
**Review done.**

2023-07-16 11:39 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        deleteRoom(mockUserJwt(host), room.roomId!!.value)
丟 User 進去，讓裡面 mockUserJwt

2023-07-16 11:51 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        deleteRoom(mockUserJwt(host), room.roomId!!.value)
這邊討論一下，我建議邏輯不要包太深，測試寫扁平化一點，讓每段測試看到 mock user 的內容，跟決定 mock 的資料。

2023-07-16 13:13 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        deleteRoom(mockUserJwt(host), room.roomId!!.value)
依照投票結果，修正在 3a32b4dcb0ef9d8a4cd0e84b19bc7bcfd5c67604

2023-07-16 13:20 UTC, Wally5077 approved these changes
**LGTM**

2023-07-16 13:21 UTC, merged