實作取得房間資訊
Game-as-a-Service/Lobby-Platform-Service pull request #124
Opened 2023-07-12 15:57 UTC by ted791029

## Why need this change? / Root cause: 
- A user want to get room information
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #64

2023-07-13 02:53 UTC, frankvicky requested changes

2023-07-13 02:53 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +    private fun findRoomById(roomId: Room.Id) =
顯式宣告回傳型別

2023-07-13 02:53 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +            room.also { presenter.present(it) }
這邊可以直接 `presenter.present(room)`

2023-07-13 14:35 UTC, Wally5077 requested changes
**Review done.**

2023-07-13 14:35 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +            val room = findRoomById(Room.Id(roomId))!!
如果找不到 Room，應該丟 NotFound

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/presenter/GetRoomPresenter.kt
> +private fun Room.Player.toGetRoomView(): GetRoomViewModel.Player =
`toViewModel`

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun giveHostAndPlayerBAreInRoomC_WhenHostGetRoomCInfo_ThenShouldReturnRoomCInfoSuccessfully() {
1. `giveHostAndPlayerBJoinedRoomC_WhenHostGetRoomC_ThenShouldGetRoomCSuccessfully`
2. 都不要稱作 `roomInfo`，稱作 room 即可

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        givenHostAndPlayersAreInTheRoom(host, playerB)
幫我順手改成：`givenHostAndPlayersJoinedTheRoom`

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun giveUserANotInRoomB_WhenUserAGetRoomBInfo_ThenShouldNotReceiveRoomBInfo(){
`giveUserANotJoinedRoomB_WhenUserAGetRoomB_ThenShouldFail`

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenShouldNotReceiveRoomInfo(Message.NOT_IN_ROOM.toString())
`thenShouldNotReceiveRoomInfo` 可以移除掉了

2023-07-13 14:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun getRoom(user: Jwt): ResultActions =
參數型態吃 User

2023-07-20 02:04 UTC, frankvicky requested changes

2023-07-20 02:04 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +            throw PlatformException("Player(" + playerId!!.value + ") is not in the room(" + roomId!!.value + ").")
使用 String interpolate

2023-07-20 02:04 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenShouldFail("Player(" + userA.id!!.value + ") is not in the room(" + testRoom.roomId!!.value + ").")
ditto
使用 String interpolate

2023-07-20 15:37 UTC, Wally5077 requested changes
**Review done.**

2023-07-20 15:37 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +            ?: throw NotFoundException.notFound(Room::class).id(roomId)
static import

2023-07-20 15:37 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomUsecase.kt
> +            val room = findRoomById(Room.Id(roomId))!!
兩個 ! 不用加，這邊已經保証回傳值不是 nullable 了

2023-07-20 15:37 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        givenHostAndPlayersJoinedTheRoom(host)
分開一下 🙏

2023-07-20 15:37 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        )
放在 `whenUserGetTheRoom` 底下，trace code 比較容易找到

2023-07-25 14:04 UTC, Wally5077 approved these changes
**LGTM**

2023-07-25 15:44 UTC, frankvicky approved these changes

2023-07-29 15:08 UTC, merged