Feature/except message
Game-as-a-Service/Lobby-Platform-Service pull request #126
Opened 2023-07-15 03:42 UTC by m1a2st

## Why need this change? / Root cause: 
- the PlatformViewModel need to have a spec 
## Changes made:
- Refactor PlatformException and Exception Handler
## Test Scope / Change impact:
- Exception Message need have a title and message
## Issue
- #119

2023-07-15 04:20 UTC, Wally5077 requested changes
**Review done.**

2023-07-15 04:20 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/aspects/PlatformExceptionHandler.kt
> +    }
變成 PlatformException 的擴充方法即可

2023-07-15 04:20 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +            fun toNotFoundMessage() = apply { this.message = "${resourceName.capitalize()} not found" }
Ｑ：為什麼需要調整成這樣？

2023-07-15 09:00 UTC, m1a2st commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/NotFoundException.kt
> +            fun toNotFoundMessage() = apply { this.message = "${resourceName.capitalize()} not found" }
A ： 希望此Builder具有一定靈活度

2023-07-15 12:54 UTC, Wally5077 requested changes
**Review done.**

2023-07-15 12:54 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/enums/ErrorType.kt
> +        notFound(resourceType).errorType(this)
用原來的方式寫

2023-07-19 03:10 UTC, frankvicky approved these changes

2023-07-22 09:11 UTC, Wally5077 requested changes
**Review done.**

2023-07-22 09:11 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +            throw PlatformException(PlatformError.USER_INPUT_INVALID, "invalid nickname: too long")
**static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +            throw PlatformException(PlatformError.USER_INPUT_INVALID, "invalid nickname: duplicated")
**static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/RegisterGameUsecase.kt
> +                    PlatformError.GAME_EXISTS,
**static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            ?: throw notFound(PlatformError.ROOM_NOT_FOUND, Room::class).id(roomId)
**static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/KickPlayerUsecase.kt
> +                PlatformError.ROOM_NOT_FOUND,
**static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +                PlatformError.PLAYER_JOIN_ROOM_ERROR,
全檔案 PlatformError **static import**

2023-07-22 09:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
> +                ?: throw notFound(PlatformError.PLAYER_NOT_FOUND, User::class)
**static import**

2023-07-25 14:05 UTC, merged