update:READ ME 優化
Game-as-a-Service/Lobby-Platform-Service pull request #127
Opened 2023-07-15 03:58 UTC by iankingh

## Why need this change? / Root cause: 
- 對READ ME 做優化
## Changes made:
-
## Test Scope / Change impact:

-
## Issue
- resolve #120

2023-07-16 04:55 UTC, mikaeloduh commented
我在 Discussion 有放一些可以拿來用用看

https://github.com/Game-as-a-Service/Lobby-Platform-Service/discussions/97#discussioncomment-6458806

2023-07-17 05:30 UTC, IamSaker requested changes

2023-07-17 05:30 UTC, IamSaker commented on README.md
> +- spring：包含應用程序的業務邏輯和應用程序的入口點，例如Web應用程序的控制器、服務和客戶端等。 包含應用程序的Spring配置和依賴項，例如數據訪問、事務管理和Web MVC等。
1. 間距格式要不要統一？
2. `application` 補充點內容進去

2023-07-17 14:49 UTC, mikaeloduh requested changes

2023-07-17 14:49 UTC, mikaeloduh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
1. Code of conduct 沒有另外放就不用
2. Discord 那邊只要水球 @Johnny850807 開設定就可以了
3. 怎麼不用 markdown 就好？

2023-07-17 15:00 UTC, ricksu978 requested changes

2023-07-17 15:21 UTC, iankingh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
3.怎麼不用 markdown 就好？ 

A：如果用markdown好像沒有辦法置中

2023-07-17 16:32 UTC, iankingh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/badge/code%20of-conduct-ff69b4.svg?style=flat" alt="Code of Conduct"></a>
瞭解先新增CODE_OF_CONDUCT.md.

之後再照這個寫看看
https://opensource.guide/code-of-conduct/

2023-07-18 01:30 UTC, IamSaker approved these changes

2023-07-18 04:40 UTC, mikaeloduh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
置中的必要性只在有 logo 為了好看，
例如：https://github.com/spaceship-prompt/spaceship-prompt/blob/master/README.md
我們沒有的話應該不需要。

2023-07-18 05:03 UTC, ricksu978 commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
Discord 設定我會再去跟水球講。

Discord badge 的連結可以放邀請連結 https://discord.gg/waterballsa

2023-07-18 13:15 UTC, iankingh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
@mikaeloduh  看大家決定 我這邊都可以調整 , 
有放比較預覽在 https://github.com/Game-as-a-Service/Lobby-Platform-Service/discussions/97

2023-07-20 05:06 UTC, ricksu978 approved these changes

2023-07-20 22:13 UTC, iankingh commented on README.md
> +  <a href="https://api.gaas.waterballsa.tw/swagger-ui/index.html"><img src="https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fapi.gaas.waterballsa.tw%2Fswagger-ui%2Fapi-docs" alt="Swagge
OK ~已修正

2023-07-21 02:20 UTC, mikaeloduh requested changes

2023-07-21 02:20 UTC, mikaeloduh commented on README.md
> +[![Discord](https://img.shields.io/discord/937992003415838761?label=Discord)](https://discord.gg/waterballsa)
把空白行拿掉

2023-07-21 02:28 UTC, iankingh commented on README.md
> +[![Discord](https://img.shields.io/discord/937992003415838761?label=Discord)](https://discord.gg/waterballsa)
OK

2023-07-21 02:52 UTC, mikaeloduh approved these changes
LGTM

2023-07-22 04:18 UTC, merged