feature: refresh access token api
Game-as-a-Service/Lobby-Platform-Service pull request #128
Opened 2023-07-15 17:51 UTC by kuoche1712003

## Why need this change? / Root cause: 
- When my access token expires, I need to renew it.
## Changes made:
- Add refresh access token api.
- OAuth2 scope: add offline_access to get a refresh token.
## Test Scope / Change impact:
- none
## Issue
- resolves https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/113

2023-07-16 11:29 UTC, frankvicky requested changes

2023-07-16 11:29 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +}
建議顯式宣告回傳型別

2023-07-16 11:29 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +            .let { JWTParser.parse(this).jwtClaimsSet.subject }
這邊應該需要 `?. `

2023-07-16 11:29 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +            ?: false
NIT：這邊我自己感覺有點難以閱讀，考慮使用 `when` 或其他方式改寫嗎？

2023-07-16 11:54 UTC, Wally5077 requested changes
**Review done.**

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +            ?: false
`?.description?.startsWith("Jwt expired at") ?: false`

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +    private fun JwtValidationException.onlyExpiredAt() =
放在調用行底下

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +    private fun String.canRefreshToken() =
ditto 放在調用行底下

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +            ?: false
`?.refreshToken != null ?: false`

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +        .attribute(HttpServletResponse::class.java.name, this.nativeResponse)
不需要用 this.

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +    fun authenticate(request: NativeWebRequest, @RequestBody payload: AuthenticateToken): AuthenticateToken{
參數換行一下

2023-07-16 11:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +        request: NativeWebRequest
交換參數順序

2023-07-16 12:21 UTC, Wally5077 requested changes
**Review done.**

2023-07-16 12:21 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/RefreshAccessTokenHandler.kt
> +
空一行就好

2023-07-16 12:29 UTC, Wally5077 approved these changes
**LGTM**

2023-07-17 01:52 UTC, frankvicky approved these changes

2023-07-17 02:31 UTC, merged