fix: jwt subject is user identity
Game-as-a-Service/Lobby-Platform-Service pull request #129
Opened 2023-07-16 16:12 UTC by kuoche1712003

## Why need this change? / Root cause: 
- Fix JWT subject misused.
## Changes made:
- Add findByIdentity method.
- Usecase use identity to find user.
- Test user add identity.
## Test Scope / Change impact:
- Room controller.
- Room usercases.
- RoomControllerTest.
## Issue
- resolves https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/125

2023-07-17 15:36 UTC, Wally5077 requested changes
**Review done.**

2023-07-17 15:36 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/KickPlayerUsecase.kt
> +            val hostPlayer = userRepository.findByIdentity(hostIdentity)?.toRoomPlayer()
`host`

2023-07-17 15:36 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/KickPlayerUsecase.kt
> +        val hostIdentity: String,
`userIdentity`

2023-07-17 15:36 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            ?: throw notFound(User::class).message()
ditto 換行

2023-07-17 15:36 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun thenPlayersShouldBeInTheRoom(roomId: Room.Id, vararg users: User) =
Ｑ：請說一下調整這裡的原因~

2023-07-17 15:38 UTC, kuoche1712003 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun thenPlayersShouldBeInTheRoom(roomId: Room.Id, vararg users: User) =
我看 IDE 是灰字就順手把他拿掉了
還是要維持原樣？

2023-07-20 14:52 UTC, Wally5077 approved these changes
**LGTM**

2023-07-22 04:18 UTC, merged