Feature/socketio testing
Game-as-a-Service/Lobby-Platform-Service pull request #135
Opened 2023-07-27 13:20 UTC by ricksu978

## Why need this change? / Root cause: 
- Frontend integration
- Make web socket testing available on production 

## Changes made:
- Add web socket

## Test Scope / Change impact:
- 

## Issue
- resolve #116 
- resolve #117

2023-07-27 13:54 UTC, Wally5077 requested changes
**Review done.**

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +    @Value("\${socketio.port}")
用 **@ConfigurationProperties** 這註解取代掉 **@Value**

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +@Configuration
中間隔一行

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/LobbyPlatformApplication.kt
> +@Import(SocketIOConfig::class)
這應該可以不用

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +//    private lateinit var socketIOServer: SocketIOServer
刪掉

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            it.sendEvent("CHAT_MESSAGE", "HELLO WORLD!")
Ｑ：這是什麼？

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            println(" CHAT_MESSAGE message is " + data)
用 logger 印出來

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            println(" CHAT_MESSAGE message is " + data)
**String literal**

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            println(" CHATROOM_JOIN message is  " + data)
ditto logger

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +class UserVM(id: String, nickname: String)
Q：說明一下這是什麼

2023-07-27 13:54 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +        socketIOServer.addEventListener("CHAT_MESSAGE", JSONObject::class.java) { client: SocketIOClient, data: JSONObject, _ ->
如果 **"CHAT_MESSAGE"** 是事件名稱，那麼不要讓這是**魔法數**，開個 interface 放這些常數

2023-07-27 14:48 UTC, wiroger9595 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +class UserVM(id: String, nickname: String)
之前用的回傳物件，現在不需要

2023-07-27 16:14 UTC, Wally5077 requested changes
**Review done.**

2023-07-28 04:35 UTC, frankvicky requested changes

2023-07-28 04:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +
排版，另外分隔一行空白即可

2023-07-28 04:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +        configuration.port = port
`apply`

2023-07-28 04:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEnum.kt
> +
刪除多餘空行

2023-07-28 04:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +
ditto，分隔一行空白即可

2023-07-28 04:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOProperties.kt
> +}
Q：為什麼不直接使用建構子？

2023-07-28 14:29 UTC, wiroger9595 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +    private val port: Int = socketIOProperties.port
為什麼不需要？
這樣怎麼跑

2023-07-30 13:18 UTC, Wally5077 requested changes
**Review done.**

2023-07-30 13:18 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/SocketIOController.kt
> +}
不需要這個類別

2023-07-30 14:52 UTC, closed without merging