Feature/update game info
Game-as-a-Service/Lobby-Platform-Service pull request #136
Opened 2023-07-30 10:01 UTC by lohas1107

## Why need this change? / Root cause: 
- As game maker, I want to update game information.
## Changes made:
- Game registration related
## Test Scope / Change impact:
- UpdateGameRegistrationUseCase
## Issue
- #33

2023-07-30 13:47 UTC, Wally5077 requested changes
**Review done.**

2023-07-30 13:47 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/GameRegistrationControllerTest.kt
> +            .content(updateGameRegistrationRequest.toJson()))
**withJson(updateGameRegistrationRequest)**

2023-07-30 13:47 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/GameRegistrationControllerTest.kt
> +        this.andExpect(status().isBadRequest)
全檔案都可以省略掉 **this.**

2023-07-30 13:47 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/GameRegistrationControllerTest.kt
> +        val result = this.andExpect(status().isOk)
**result** -> **view**

2023-07-30 14:06 UTC, frankvicky approved these changes

2023-08-06 11:36 UTC, IamSaker approved these changes

2023-08-06 11:42 UTC, merged