更新socket io
Game-as-a-Service/Lobby-Platform-Service pull request #137
Opened 2023-07-30 14:53 UTC by wiroger9595

## Why need this change? / Root cause: 
- Frontend integration
- Make web socket testing available on production 

## Changes made:
- Add web socket

## Test Scope / Change impact:
- 

## Issue
- resolve #116

2023-08-01 07:05 UTC, Wally5077 requested changes
**Review done.**

2023-08-01 07:05 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/SecurityConfig.kt
> -            .antMatchers("/swagger-ui/**", "/favicon.ico").permitAll()
可以變回這樣了

2023-08-01 07:05 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/ServerCommandLineRunner.kt
> +@ConditionalOnProperty(prefix = "socketio", name = ["active"], havingValue = "true")
1. **enable**
2. 不用陣列，給個字串就可了

2023-08-01 07:05 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/ServerCommandLineRunner.kt
> +        if (System.getProperty("skipServerCommandLineRunner") == null) {
1. **skipServerCommandLineRunner** 不會有這個環境變數了
2. **SocketIOServer** 是否有查詢狀態的函數能用？

2023-08-01 07:05 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +
刪除空行

2023-08-01 12:35 UTC, frankvicky requested changes

2023-08-01 12:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOConfig.kt
> +
使用 `apply { ... }`

2023-08-01 12:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +//        }
用不到直接刪掉

2023-08-01 12:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            logger.info(" Received message: $data from client: ${client.sessionId}")
刪除多餘空格

2023-08-01 12:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOProperties.kt
> +}
```kotlin
data class SocketIOProperties (
    val host: String = "127.0.0.1",
    val port: Int = 9001
)
```

這如果只是一個單純的資料結構，改成使用 `data class`

2023-08-01 15:02 UTC, Wally5077 requested changes
**Review done.**

2023-08-08 09:52 UTC, closed without merging

2023-08-08 10:11 UTC, wiroger9595 commented
reopen

2023-08-08 10:11 UTC, wiroger9595 commented
reopen comment