:fix rooms pageNum and return format
Game-as-a-Service/Lobby-Platform-Service pull request #145
Opened 2023-08-13 13:55 UTC by m1a2st

## Why need this change? / Root cause: 
- according to frontend's request
## Changes made:
- page logic and return api format
## Test Scope / Change impact:
- RoomControllerTest
## Issue
- #143 #144

2023-08-13 16:29 UTC, Wally5077 requested changes
**Review done.**

2023-08-13 16:29 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        // 這邊為了配合前端，因為他們的 page 是從 1 開始，所以這邊要減 1
請前端他們帶上來 0

2023-08-13 16:29 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/presenter/GetRoomsPresenter.kt
> +        // 這邊為了配合前端，因為他們的 page 是從 1 開始，所以這邊要加 1
ditto 請前端他們帶上來 0

2023-08-13 16:29 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .andDo { println(it.response.contentAsString) }
Ｑ：這是測試程式碼？

2023-08-13 16:29 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/models/TestGetRoomsRequest.kt
> +    // 這邊為了配合前端，因為他們的 page 是從 1 開始，所以這邊要減 1
ditto 請前端他們帶上來 0

2023-08-14 03:43 UTC, frankvicky requested changes

2023-08-14 03:43 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .andDo { println(it.response.contentAsString) }
Q：印出來的目的？

2023-08-17 13:53 UTC, Wally5077 requested changes
**Review done.**

2023-08-17 14:13 UTC, Wally5077 approved these changes
**LGTM**

2023-08-18 04:16 UTC, frankvicky approved these changes

2023-08-18 05:25 UTC, merged