:sparkles: 新增 LogData Entity
Game-as-a-Service/Lobby-Platform-Service pull request #146
Opened 2023-08-14 12:20 UTC by frankvicky

## Why need this change? / Root cause: 
- 為日誌功能做準備
## Changes made:
- LogData
## Test Scope / Change impact:
- spring module
## Issue
- none

2023-08-14 13:07 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/LogData.kt
> +@Document
為 **Document** 取個名字吧

2023-08-15 02:59 UTC, ricksu978 commented
@frankvicky @Wally5077 

這個 PR 需要我的 approval 才能 merge 喔。

我晚點再來仔細看過，從需求功能面來看，有些沒有達到。

2023-08-15 15:48 UTC, ricksu978 commented
@frankvicky 
詳細需求寫在 https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/148

新需求 4.5 / 4.6 / 5

2023-08-16 03:00 UTC, Wally5077 approved these changes
**LGTM**

2023-08-16 12:29 UTC, ricksu978 requested changes

2023-08-16 12:29 UTC, ricksu978 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameDevelopmentLog.kt
> +)
ditto 新需求請看 #147

2023-08-25 16:19 UTC, Wally5077 requested changes
**Review done.**

2023-08-25 16:19 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/LogCategory.kt
> +    var id: String,
Ｑ：這需要標記 **@Id** 吧？

2023-08-25 16:19 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameDevelopmentLog.kt
> +    val author: String,
Ｑ：這個是「非平台用戶」也能發嗎？

2023-08-26 03:42 UTC, ricksu978 requested changes

2023-08-26 03:42 UTC, ricksu978 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/GameDevelopmentLog.kt
> +)
如果我要拿一個遊戲的所有日誌，該怎麼拿呢?

2023-08-28 14:11 UTC, ricksu978 approved these changes
LGTM

2023-08-29 15:27 UTC, Wally5077 approved these changes
**LGTM**

2023-08-30 00:47 UTC, merged