實作最後一人離開房間後則自動關閉房間
Game-as-a-Service/Lobby-Platform-Service pull request #149
Opened 2023-08-17 13:05 UTC by ted791029

## Why need this change? / Root cause: 
-Readiness oriented room host
## Changes made:
-Room related
## Test Scope / Change impact:
-RoomController
## Issue
-#139

2023-08-17 13:21 UTC, Wally5077 requested changes
**Review done.**

2023-08-17 13:21 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            if (room.isEmpty()) roomRepository.deleteById(room.roomId!!)
```kotlin
room.leaveRoom(player)

if (room.isEmpty()) {
    roomRepository.deleteById(room)
} else {
    roomRepository.leaveRoom(room)
}
```

2023-08-18 01:32 UTC, Wally5077 requested changes
**Review done.**

2023-08-18 01:32 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +                roomRepository.deleteById(room.roomId!!)
昨天忘了補充，請幫我將 **deleteById** 改成下方這樣 🙏 
```kotlin
roomRepository.closeRoom(room)
```

2023-08-18 04:18 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +            }
NIT：可以考慮用 `when`

2023-08-19 15:01 UTC, Wally5077 approved these changes
**LGTM**

2023-08-20 02:23 UTC, merged