:feature create user
Game-as-a-Service/Lobby-Platform-Service pull request #155
Opened 2023-08-21 12:24 UTC by m1a2st

## Why need this change? / Root cause: 
- proxy server need an api to create user
## Changes made:
- add an api
## Test Scope / Change impact:
- user controller test
## Issue
- #152

2023-08-21 15:14 UTC, Wally5077 requested changes
**Review done.**

2023-08-21 15:14 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    fun givenUserNotLoginAtProxyService_whenUserCreateAnUser_thenUserShouldBeCreatedFail() {
ditto `UserCreateAnUser`

2023-08-21 15:14 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
>                  .content(updateUserRequest.toJson())
1. inline
2. **withJson**

2023-08-21 15:14 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +            .also { assertThat(it!!.email).isEqualTo(email) }
宣告一個變數測，這裡用 also 沒有優點

2023-08-21 15:19 UTC, m1a2st commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    fun givenUserLoginAtProxyService_whenUserCreateAnUserWithJwt_thenUserShouldBeCreatedSuccessful() {
是想要表示這個請求有沒有帶 JWT 的 Token ，因為 Create User 會需要用到 JWT token 的 Subject

2023-08-22 03:15 UTC, Wally5077 approved these changes
**LGTM**

2023-08-22 05:49 UTC, merged