Feature/fast join
Game-as-a-Service/Lobby-Platform-Service pull request #159
Opened 2023-09-03 13:49 UTC by kuoche1712003

## Why need this change? / Root cause: 
- As a user, I want a fast way to join rooms so that I can play games.
## Changes made:
- Add fast join room api.
## Test Scope / Change impact:
- RoomController
## Issue
- #158

2023-09-10 10:39 UTC, frankvicky requested changes

2023-09-10 10:39 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/FastJoinRoomUseCase.kt
> +            }
這段可以封裝，然後給予一個具有領域意義的命名。

2023-09-10 14:28 UTC, Wally5077 requested changes
**Review done.**

2023-09-10 14:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
1. 不需要 this
2. room 已經是創建過了，因此 roomId 不可能 null
3. roomId 的型態直接給 RoomId
4. 參數分別給 Room、GameRegistration、User 即可
5. 如果要轉成 JsonNode，可以考慮換成轉 FastJoinRoomViewModel

2023-09-10 14:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenShouldFastJoinRoom(gameId = testGame.id!!, playerId = Player.Id(testUser.id!!.value))
函數命名叫做 **ThenShouldCreateRoom**，那麼就不應該使用 **thenShouldFastJoinRoom**

2023-09-10 14:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +
是不是還少測試了，已加入過房間的 Player，又快速加入房間的案例？

2023-09-10 14:32 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    @PostMapping("/rooms")
fastJoin api path 為 `/rooms:fastJoin`
若在 Controller class 設定 `RequestMapping("/rooms")`
試了很久下面沒辦法 mapping 到 path

2023-09-10 14:39 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            .firstOrNull { it.players.size < it.maxPlayers && it.password == null }
確實是想要按照創建房間的時間排序, 目前沒有該屬性
所以想到按照 mongo _id 排序其實就是照 create time 排序

2023-09-10 15:06 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            .firstOrNull { it.players.size < it.maxPlayers && it.password == null }
恩... 有指定了 @Id 是不是就沒有了 _id 的欄位了

2023-09-16 15:36 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    @PostMapping("/rooms")
Q：那有試過你的方法給 API Path 給 `":fastJoin"` 嗎？

2023-09-16 15:42 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    @PostMapping("/rooms")
有喔 我有試過 但一樣沒辦法 mapping 到
會直接跑 404

2023-09-17 03:07 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            .firstOrNull { it.players.size < it.maxPlayers && it.password == null }
關於時間問題，建議在大平台會議上與同仁討論，看看要不要額外加入「創建時間」的欄位吧 ~

2023-09-17 04:01 UTC, Wally5077 requested changes
**Review done.**

2023-09-17 04:01 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        assertTrue(actualJoinedRoom.hasPlayer(playerId))
這得直接判斷 player 是不是 host

2023-09-23 13:19 UTC, kuoche1712003 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/FastJoinRoomUseCase.kt
> +            roomRepository.update(this)
這個意思是直接將 JoinRoomUsecase inject 到 FastJoinUsecase 裏
然後直接調用他的 excute method 嗎？
想取得 Room 修改 JoinRoomUsecase 但他是透過 presenter 拿到的
那此時我這個 usecase 應該怎麼使用

2023-09-24 06:17 UTC, Wally5077 requested changes
**Review done.**

2023-09-24 06:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenMahjongGameRoom_WhenUserBFastJoinWithMahjongGame_ThenUserBShouldJoinedRoom() {
**WhenUserBFastJoinMahjongGameRoom**

2023-09-24 06:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenFullMahjongGameRoom_WhenUserEFastJoinWithMahjongGame_ThenUserEShouldCreateRoom() {
**WhenUserEFastJoinMahjongGameRoom**

2023-09-24 06:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        Given: Mahjong game room A and mahjong game room B exist, room A was created earlier than room B
**Both Mahjong game room A and mahjong game room B are created**

2023-09-24 06:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        Then: User C should be joined room A
**should join**

2023-09-24 06:43 UTC, Wally5077 approved these changes
**LGTM**

2023-09-24 06:54 UTC, frankvicky approved these changes

2023-09-24 07:00 UTC, merged