docs: add English version README
Game-as-a-Service/Lobby-Platform-Service pull request #160
Opened 2023-09-07 10:57 UTC by mikaeloduh

## Why need this change? / Root cause: 
-
## Changes made:
-
## Test Scope / Change impact:
-
## Issue
-

2023-09-10 09:55 UTC, ricksu978 requested changes
Review Done.

2023-09-10 09:55 UTC, ricksu978 commented on README-en.md
> +Game as a Service is an open source, community-based project aimed at demonstrating the best software engineering methodologies, such as Domain-Driven Design (DDD), Behavior-Driven Development (BDD),
> Game as a Service is an open source
1. 你後面段落有引用 GaaS，所以前面這邊打全名時加個縮寫比較好 `Game as a Service (GaaS)`

> demonstrating the best software engineering methodologies
2. `the best` 這邊需要修飾一下， 可以試試看 ChatGPT 的建議

> Feel free to check around the code.
3.  ~~check around~~ check out

2023-09-10 09:55 UTC, ricksu978 commented on README-en.md
> +Lobby-Platform-Service supports the backend service of GaaS, providing a gaming portal and a social community platform.
Lobby-Platform-Service ~~supports~~ is the backend service of GaaS,

2023-10-01 07:19 UTC, mikaeloduh commented on README-en.md
> +Game as a Service is an open source, community-based project aimed at demonstrating the best software engineering methodologies, such as Domain-Driven Design (DDD), Behavior-Driven Development (BDD),
修改在 ecc8fcf4f9356cc02d6a161320d465ce3b435295

2023-10-01 07:19 UTC, mikaeloduh commented on README-en.md
> +Lobby-Platform-Service supports the backend service of GaaS, providing a gaming portal and a social community platform.
同上

2023-10-01 09:59 UTC, ricksu978 approved these changes

2023-10-01 10:07 UTC, merged