update join room, create room and leave room
Game-as-a-Service/Lobby-Platform-Service pull request #174
Opened 2023-09-29 05:23 UTC by wiroger9595

## Why need this change? / Root cause: 
- create room, join room and leave room for websocket
## Changes made:
- add two event
## Test Scope / Change impact:
-  socket io can only use postman to test event
## Issue
- #168

2023-09-29 05:48 UTC, Wally5077 requested changes
**Review done.**

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                logger.error("并没有人连接上。。。")
Q：真的會需要印這個訊息嗎

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            { client: SocketIOClient, chatMessage: JSONObject, _ ->
如果套件能幫我們轉成 **JSONObject**，那麼理應也能轉成我們自己定義的類別，建議這邊自己定義類別，而不是 **JSONObject**

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                client: SocketIOClient, getJoinRoom: JSONObject, _ ->
ditto 自定義類別

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            // roomSize == 0, create room  else join room
未知註解刪掉

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                //client.send()
ditto 未知註解

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                client: SocketIOClient, leaveRoom: JSONObject, _ ->
ditto 自定義類別

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +        socketIOServer.addEventListener("DISCONNECT", JSONObject::class.java) {
ditto 自定義類別

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                logger.info("用户：{}", client.sessionId, "you are the host ")
改用 String literals

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                logger.info(" room size is : ${client.getCurrentRoomSize(target.toString())}")
ditto String literals

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            println(" client is leaven room with key disconnect")
改用 logger

2023-09-29 05:48 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            println("Server disconnected on the server side")
ditto logger

2023-09-29 06:23 UTC, frankvicky requested changes

2023-09-29 06:23 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +                logger.error("并没有人连接上。。。")
如果是找來得範例要調整成繁中喔

2023-09-29 06:23 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            { client: SocketIOClient, chatMessage: JSONObject, _ ->
Lambda 括號感覺不是在這邊，記得跑 Ktlint 或 IJ 的排版

2023-09-29 15:16 UTC, wiroger9595 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            // roomSize == 0, create room  else join room
後續可能會用到

2023-10-01 13:17 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +            // roomSize == 0, create room  else join room
那這需要說明

2023-10-01 13:23 UTC, Wally5077 requested changes
**Review done.**

2023-10-16 11:40 UTC, frankvicky requested changes

2023-10-16 11:40 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +
刪除沒必要的空行，排版以一行分隔為原則。

2023-10-16 11:40 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventHandler.kt
> +) {
```kotlin
class SocketIOEventHandler(
    private val socketIOServer: SocketIOServer,
    protected val roomRepository: RoomRepository,
    protected val userRepository: UserRepository,
) {
````

2023-10-16 11:40 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/socketio/SocketIOEventName.kt
> +}
ditto，刪除不必要的空行。

2023-10-16 15:45 UTC, wiroger9595 commented
merge event bus

2023-10-16 16:56 UTC, frankvicky approved these changes

2023-10-17 11:29 UTC, merged