feat: [websocket] 看見其他玩家加入/離開(#154)"
Game-as-a-Service/Lobby-Platform-Service pull request #183
Opened 2023-10-15 07:01 UTC by cooper-car

## Why need this change? / Root cause: 
- web-socket 
  - user joined room event
  - user leaved room event
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #154

2023-10-15 12:07 UTC, Wally5077 requested changes
**Review done.**

2023-10-15 12:07 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +    private fun Room.joinRoomEvent(
Room.joinPlayer 時，回傳 **PlayerJoinedRoomEvent**

2023-10-15 12:07 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +    }
room.leaveRoom，回傳 **PlayerLeavedRoomEvent**

2023-10-15 12:07 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/UserJoinedRoomEvent.kt
> +        data class UserInfo(
直接叫 Player 就好~

2023-10-15 12:07 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/UserLeavedRoomEvent.kt
> +        data class UserInfo(
ditto Player

2023-10-15 14:47 UTC, cooper-car commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +    private fun Room.joinRoomEvent(
已修正

2023-10-15 14:47 UTC, cooper-car commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/LeaveRoomUsecase.kt
> +    }
已修正

2023-10-15 14:47 UTC, cooper-car commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/UserJoinedRoomEvent.kt
> +        data class UserInfo(
已修正

2023-10-15 14:47 UTC, cooper-car commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/UserLeavedRoomEvent.kt
> +        data class UserInfo(
已修正

2023-10-16 08:55 UTC, frankvicky approved these changes

2023-10-16 15:41 UTC, merged