1.實作遊戲結束功能
Game-as-a-Service/Lobby-Platform-Service pull request #185
Opened 2023-11-01 14:19 UTC by ted791029

## Why need this change? / Root cause: 
- end-game
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #184

2023-11-04 13:57 UTC, frankvicky requested changes

2023-11-04 13:57 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    private fun playersCancelReady() {
`cancelReadyForNonHostPlayers`

2023-11-04 13:57 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +
```kotlin
    private fun givenPlayersArePlayingInRoom(host: Player, vararg players: Player): Room {
        players.forEach { it.ready() }
        val allPlayers = mutableListOf(host, *players)
        testRoom = createRoom(host = host, players = allPlayers, status = PLAYING)
        return testRoom
    }
```

2023-11-05 03:20 UTC, ted791029 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    private fun playersCancelReady() {
已修正

2023-11-05 03:22 UTC, ted791029 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +
已修正

2023-11-05 05:21 UTC, frankvicky approved these changes

2023-11-05 10:41 UTC, merged