使用第三方登入後，新增使用者
Game-as-a-Service/Lobby-Platform-Service pull request #50
Opened 2023-05-07 10:18 UTC by lohas1107

## Why need this change? / Root cause: 
- As game lobby, when new user login, then create user
## Changes made:
- New Feature: Create new user
## Test Scope / Change impact:
- OAuth2Controller
## Issue
- resolved #24

2023-05-08 07:29 UTC, Wally5077 requested changes
Review done.

2023-05-08 07:29 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +            val event = userRepository.createUser(request.toUser()).toUserCreatedEvent()
```kotlin
val user = userRepository.createUser(request.toUser())
val event = user.toUserCreatedEvent()
```

2023-05-08 07:29 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        userRepository.existsUserByEmail(request.email) -> {}
這邊如果存在的話，就是錯誤的話，應該拋例外，終止創建平台用戶流程

2023-05-08 07:29 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
>      @GetMapping("/")
`@GetMapping` 就好了

2023-05-08 07:29 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +fun OidcUser?.toRequest(): CreateUserUseCase.Request = CreateUserUseCase.Request(
這擴充方法應當是 private 的 scope，否則其他不該用的地方也能用到

2023-05-08 07:29 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2ControllerTest.kt
> +        Assertions.assertThat(userRepository.existsUserByEmail(userInfo.email)).isEqualTo(isExists)
static import

2023-05-08 07:29 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2ControllerTest.kt
> +    private fun OidcUser.userExists(isExists: Boolean): OidcUser = this.also {
assertUserExists

2023-05-08 07:29 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        fun toUser(): User = User(null, email, "")
Q：UserId 給 null 的原因是為什麼？

2023-05-08 07:50 UTC, frankvicky requested changes

2023-05-08 07:50 UTC, frankvicky commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        fun toUser(): User = User(null, email, "")
`User(email = email, nickname = "")`

2023-05-08 07:50 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2ControllerTest.kt
> +    lateinit var eventBus: EventBus
可以把改成
```kotlin
class OAuth2ControllerTest(
    @Autowired val userRepository: UserRepository,
    @Autowired val mockMvc: MockMvc
) {
    @MockBean
    lateinit var eventBus: EventBus
}
```

使用 val 進行依賴注入是 best practice

2023-05-21 00:54 UTC, lohas1107 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        userRepository.existsUserByEmail(request.email) -> {}
這邊使用者存在，是指已建立過的使用者再度登入平台，應該不算是錯誤，
#50 issue 內描述在這種情況是不做事。

2023-05-21 05:27 UTC, Wally5077 requested changes
Review done.

2023-05-21 05:27 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        fun toUser(): User = User(email = email, nickname = "")
如果沒有 nickname，就讓 User 建構子預設 nickname 是空字串

2023-05-21 05:27 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/UserCreatedEvent.kt
> +    val nickname: String
`val nickname: String = ""`

2023-05-21 05:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +@ActiveProfiles(profiles = ["dev"])
現在可以把這個拔掉

2023-05-21 05:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +        givenInvalidUserInfo().thenLoginFailed()
```kotlin
givenInvalidUserInfo()
    .whenLogin
    .thenShouldLoginFailed()
```

2023-05-21 05:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .loginSuccessfully().assertUserExists(true)
```kotlin
givenNewUserInfo().assertUserNotExists()
    .whenLogin()
    .thenShouldLoginSuccessfully()
```

2023-05-21 05:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .loginSuccessfully().assertUserExists(true)
```kotlin
givenNewUserInfo().assertUserExists()
    .whenLogin()
    .thenShouldLoginSuccessfully()
```

2023-05-21 13:02 UTC, frankvicky approved these changes
LGTM

2023-05-21 13:13 UTC, Wally5077 approved these changes
LGTM

2023-05-22 02:43 UTC, merged