Feature/get room list
Game-as-a-Service/Lobby-Platform-Service pull request #72
Opened 2023-05-27 09:26 UTC by m1a2st

## Why need this change? / Root cause: 
- A user want to see room list
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #63

2023-06-20 08:16 UTC, frankvicky requested changes

2023-06-20 08:16 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
GET 請求不該夾帶 Body

2023-06-20 08:16 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +private fun List<Room>.toRoomsViewModel(request: RoomController.GetRoomsRequest): RoomController.GetRoomsViewModel =
static import `RoomController.GetRoomsRequest`, `RoomController.GetRoomsViewModel`

2023-06-20 08:16 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .andDo { print(it) }
這個用意是？

2023-06-20 09:07 UTC, Wally5077 requested changes
Review done.

2023-06-20 09:07 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenUserAIsLoginAndThereAreRoom01AndRoom02_WhenUserALookRoomList_ThenShouldSeeTheRoom01AndRoom02() {
```java
givenWaitingRoomBAndWaitingRoomC_WhenUserAVisitLobby_ThenShouldHaveRoomBAndRoomC
```

2023-06-20 09:07 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenSeeRoomListHaveTwoRooms()
請根據上述留言的方法名調整變數

2023-06-20 09:07 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/models/TestGetRoomsRequest.kt
> +    val perPage: Int
ditto offset

2023-06-21 09:28 UTC, Wally5077 requested changes
Review done.

2023-06-21 09:28 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
> +        fun toPageable(): Pagination<Any> = Pagination(page, offset)
`toPagination`

2023-06-21 09:28 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/events/GetRoomsEvent.kt
> +    data class Meta(
**Page**

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        val status: String,
status 值域也要驗證

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    )
這些邏輯獨立一個檔案 GetRoomsPresenter，否則太擠了

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +            .let { Pagination(page.page, page.offset, it.content) }
擴充 `Pageable.toPagination`

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        whenUserAVisitLobbyhenVisitLobby(TestGetRoomsRequest("WAITING", 0, 10), userA)
`whenUserAVisitLobbyhenVisitLobby` 擴充成 `TestGetRoomsRequest` 的方法

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
`givenWaitingRoom(user: User)`，外面給 User，不要寫死在方法內

2023-06-21 09:28 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
方法名不要寫死是 RoomB 和 RoomC，房間長度也不會固定是 2，變動之處從方法參數傳入

2023-06-22 13:52 UTC, frankvicky approved these changes
LGTM

2023-06-22 15:26 UTC, Wally5077 requested changes
Review done.

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/presenter/GetRoomsPresenter.kt
> +    )
1. 應該擴充 `GetRoomsEvent.Page`
2. private func

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringRoomRepositoryImpl.kt
> +        .map { it.toDomain() }.toPagination()
`toPagination()` 換行

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        whenUserAVisitLobbyThenVisitLobby(request, userA)
`request.whenUserVisitLobbyThenVisitLobby(userA)`

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        givenWaitingRoomBAndWaitingRoomC(userB, userC)
`givenWaitingRooms()`

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
由外部決定多少人創造幾個房間
`private fun givenWaitingRoomBAndWaitingRoomC(vararg user: User)`

2023-06-22 15:26 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun ResultActions.thenShouldHaveRooms(countOfRoom: Int, currentPlayers: Int) {
這邊不用查參數，在驗證方法內直接用資料庫資料和 json 欄位比值就好

2023-06-22 15:26 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
> +        roomRepository.findByStatus(request.status, request.toPagination()).toGetRoomEvent()
`toGetRoomEvent()` 換行

2023-06-22 15:26 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
> +                eventBus.broadcast(event)
Q：這為什麼需要推播？

2023-06-23 02:59 UTC, Wally5077 requested changes
Review done.

2023-06-23 02:59 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
> +        fun toPagination(): Pagination<Any> = Pagination(page, offset)
private

2023-06-23 02:59 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        request.whenUserAVisitLobby(request, userA)
`request` 不用再傳進去了

2023-06-23 02:59 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun givenWaitingRooms(vararg user: User) =
users

2023-06-23 02:59 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .andExpect(jsonPath("$.rooms[0].minPlayers").value(testRoom.minPlayers))
根據房間數量比較內容

2023-06-23 07:26 UTC, Wally5077 requested changes
Review done.

2023-06-23 07:26 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetRoomsUseCase.kt
> +            .also { presenter.present(it) }
present 一個 `Pagination` 就好，不需要 `GetRoomsEvent`

2023-06-23 08:54 UTC, Wally5077 approved these changes
LGTM

2023-06-23 08:56 UTC, merged