Feature/join room full
Game-as-a-Service/Lobby-Platform-Service pull request #73
Opened 2023-05-28 05:21 UTC by mikaeloduh

## Why need this change? / Root cause: 
- Exception when room is full
## Changes made:
- Add maximum player validation 
## Test Scope / Change impact:
- Room domain
## Ticket
- https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/54

2023-05-28 05:28 UTC, mikaeloduh commented
第一次寫 Spring Kotlin，請小力鞭。

2023-06-25 11:03 UTC, frankvicky requested changes

2023-06-25 11:10 UTC, Wally5077 requested changes
**Review done.**

2023-06-25 11:10 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            throw PlatformException("The room (${roomId}) is full. Please select another room or try again later.")
大括號包起來

2023-06-25 11:10 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            room.validateRoomIsFull()
**validateFullRoom**

2023-06-25 11:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenRoomIsNotFull_whenUserTriesToJoin_ThenShouldSucceed() {
**givenRoomIsNotFull_whenUserJoinRoom_ThenShouldSucceed**

2023-06-25 11:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenRoomIsFull_whenUserTriesToJoin_ThenShouldFail() {
**givenRoomIsFull_whenUserJoinRoom_ThenShouldFail**

2023-06-25 11:50 UTC, mikaeloduh commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    }
修正在 1161adde82c1ae55cfed01a0b9b3b788fdbfab9f

2023-06-25 11:51 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            throw PlatformException("The room (${roomId}) is full. Please select another room or try again later.")
修正在 29abe34d4d5214158facb3df10a57e4db5fea6f4

2023-06-25 11:51 UTC, mikaeloduh commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            room.validateRoomIsFull()
修正在 647f2d40f893e0873159eeb8c1125a2215012496

2023-06-25 11:51 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenRoomIsFull_whenUserTriesToJoin_ThenShouldFail() {
修正在 1d0796e2f93188ae9ae6dac5969712d7cb751eac

2023-06-25 11:51 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun givenRoomIsNotFull_whenUserTriesToJoin_ThenShouldSucceed() {
修正在 1d0796e2f93188ae9ae6dac5969712d7cb751eac

2023-07-01 12:55 UTC, frankvicky approved these changes

2023-07-01 15:35 UTC, Wally5077 approved these changes
**LGTM**

2023-07-01 15:42 UTC, merged