feat : 新增swagger-ui 開放給所有人看
Game-as-a-Service/Lobby-Platform-Service pull request #75
Opened 2023-05-28 15:43 UTC by m1a2st

## Why need this change? / Root cause: 
- open swagger-ui to everyone
## Changes made:
- security and application.yml
## Test Scope / Change impact:
- open swagger-ui
## Issue
- #68

2023-05-30 10:02 UTC, ricksu978 requested changes

2023-05-30 10:02 UTC, ricksu978 commented on spring/src/main/resources/application-dev.yaml
> +    tags-sorter: alpha
放 `application-dev.yaml` 只有開發環境會有，我們佈署到 production ，swagger 也要公開。

2023-05-30 10:51 UTC, m1a2st commented on spring/src/main/resources/application-dev.yaml
> +    tags-sorter: alpha
已更正

2023-05-30 15:31 UTC, Wally5077 requested changes
Review done.

2023-05-30 15:31 UTC, Wally5077 commented on spring/src/main/resources/application-dev.yaml
> +    tags-sorter: alpha
這邊改成放在 `application.yaml` 後，配置都會繼承下來，因此這邊的配置可以移除了。

2023-05-30 15:33 UTC, frankvicky approved these changes
LTGM

2023-05-30 23:08 UTC, m1a2st commented on spring/src/main/resources/application-dev.yaml
> +    tags-sorter: alpha
已更正

2023-05-31 15:49 UTC, ricksu978 approved these changes
LGTM

2023-05-31 15:51 UTC, ricksu978 requested changes
PR 跟 `main` 有衝突，可能要 rebase 喔

2023-06-01 12:49 UTC, m1a2st commented
已 rebase

2023-06-04 10:06 UTC, ricksu978 approved these changes

2023-06-04 10:07 UTC, merged