健康檢測 API
Game-as-a-Service/Lobby-Platform-Service pull request #81
Opened 2023-05-30 12:55 UTC by mikaeloduh

## Why need this change? / Root cause: 
- Health check API 

## Changes made:
- Adds `GET /health` API

## Test Scope / Change impact:
- `HealthCheckController`

## Issue
- https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/66

2023-05-30 13:59 UTC, frankvicky requested changes

2023-05-30 13:59 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/HealthCheckControllerTest.kt
> +class HealthCheckControllerTest {
繼承 `AbstractSpringBootTest` ，具體可以參考其他測試。

2023-05-30 14:53 UTC, mikaeloduh commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/HealthCheckControllerTest.kt
> +class HealthCheckControllerTest {
已修改在 https://github.com/Game-as-a-Service/Lobby-Platform-Service/pull/81/commits/b16a7594185207ac4c3cf9b0702f6872c8dd6332

2023-05-30 15:01 UTC, Wally5077 requested changes
Review done.

2023-05-30 15:01 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/HealthCheckController.kt
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
`static import`

2023-05-30 15:55 UTC, mikaeloduh commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/HealthCheckController.kt
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
已修改在 https://github.com/Game-as-a-Service/Lobby-Platform-Service/pull/81/commits/55d55a9176002ebf42015faeb3cd172396639258

2023-05-31 02:11 UTC, frankvicky approved these changes
LGTM

2023-05-31 12:32 UTC, Wally5077 approved these changes
LGTM

2023-06-01 10:15 UTC, merged