實作加入房間
Game-as-a-Service/Lobby-Platform-Service pull request #83
Opened 2023-05-31 13:28 UTC by ted791029

## Why need this change? / Root cause: 
- A user want to jon a game room
## Changes made:
- Room related
## Test Scope / Change impact:
- RoomController
## Issue
- #27 #53

2023-05-31 14:18 UTC, frankvicky requested changes

2023-05-31 14:18 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    }
這裡命名意圖不清

2023-05-31 14:18 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/PlayerNumberCompatibilityException.kt
> +class PlayerNumberCompatibilityException(message: String) : PlatformException(message)
目前除非特別需要，不然都使用 `PlatformException`

2023-05-31 14:18 UTC, frankvicky commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/WrongRoomPasswordException.kt
> +class WrongRoomPasswordException() : PlatformException("wrong password")
ditto

2023-05-31 14:18 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(JoinRoomViewModel(e.message!!))
`HttpStatus` Static Import

2023-05-31 14:18 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    class JoinRoomPresenter : JoinRoomUsecase.Presenter {
請參考上面提到的 `Presenter` 問題

2023-05-31 14:18 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/models/TestJoinRoomRequest.kt
> +    }
用 `AbstractSpringBootTest` 裡的 `toJson` 方法就好

2023-05-31 14:32 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +    }
這個主要是想將所有join room的所有驗證都放這邊，像是人數達上限無法加入之類的，所以是希望一個驗證就一個function嗎?

2023-05-31 14:55 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +    }
已修正

2023-05-31 14:55 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +        room.players.add(player)
已修正

2023-05-31 14:56 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            ?.let { Room.Player(Room.Player.Id(it.id!!.value), it.nickname) }
已修正

2023-05-31 14:57 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +    }
已修正

2023-05-31 15:11 UTC, ted791029 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +                        ?: throw PlatformException("User not found.")
不應該包含更新使用者暱稱的程式，已刪除

2023-05-31 16:11 UTC, Wally5077 requested changes
Review done.

2023-05-31 16:11 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/UpdateUserUseCase.kt
> +class UpdateUserUseCase(
NIT：這段程式真的涵蓋在負責的 issue 之中吧？

2023-05-31 16:11 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/PlayerNumberCompatibilityException.kt
> +class PlayerNumberCompatibilityException(message: String) : PlatformException(message)
Ｑ：這類別名中文是什麼意思？

2023-05-31 16:11 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(JoinRoomViewModel(e.message!!))
用「全局例外處理」類別去控制這段

2023-05-31 16:11 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    fun joinRoom(@PathVariable roomId: String, @RequestBody request: JoinRoomRequest, @AuthenticationPrincipal principal: OidcUser?): ResponseEntity<Any> {
1. 方法參數換行
2. 按下方順序排列
```
1. @AuthenticationPrincipal principal
2. @PathVariable roomId
3. @RequestBody request
```

2023-05-31 16:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenJoinRoomSuccessfully()
`given & when & then` 的程式應該分三段

2023-05-31 16:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenWrongPassword()
ditto 分三段

2023-05-31 16:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenJoinRoomSuccessfully()
ditto 分三段

2023-05-31 16:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/models/TestJoinRoomRequest.kt
> +    }
```kotlin
return mapOf("password" to password).toJson()
```

2023-06-01 01:51 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +            ?: throw NotFoundException("Room(${roomId.value}) not found.")
@ted791029 使用 `NotFoundException` 裡面的 Builder，可以參考一下先前功能的相關用法

2023-06-03 11:15 UTC, frankvicky requested changes

2023-06-03 11:15 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun OidcUser.WhenUserBJoinTheRoom(password: String? = null):ResultActions{
命名函數請遵守駝峰式

2023-06-03 11:15 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            host = Room.Player(Room.Player.Id(testUser.id!!.value), testUser.nickname),
`Room` static import

2023-06-03 11:15 UTC, frankvicky commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun OidcUser.WhenUserBJoinTheRoom(password: String? = null):ResultActions{
函數之間請用一個空行分隔

2023-06-03 16:04 UTC, Wally5077 requested changes
Review done.

2023-06-03 16:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenWrongPassword()
按照上述測試提到的建議調整一版

2023-06-03 16:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenJoinRoomSuccessfully()
ditto 按照上述測試提到的建議調整一版

2023-06-03 16:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun mockOidcUser(id: String, name: String, email: String): OidcUser {
需要從參數傳入的原因是什麼？

2023-06-03 16:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun createTestRoom(password: String? = null): Room = roomRepository.createRoom(
**以下闡述套用在整個類別內**

1. 測試方法放最上方
2. 這些 mockMvc 方法放所有測試方法下
3. 測試方法之外的方法，按照方法調用順序擺放方法

2023-06-09 07:11 UTC, Wally5077 requested changes
Review done.

2023-06-09 07:11 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/Room.kt
> +    }
排版

2023-06-09 07:11 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/aspects/PlatformExceptionHandler.kt
> +        return ResponseEntity(mapOf("message" to (exception.message ?: "")), BAD_REQUEST)
`mapOf("message" to (exception.message ?: ""))`

2023-06-09 07:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +                .with(oidcLogin().oidcUser(mockOidcUser(testUser.id!!.value, testUser.nickname, testUser.email)))
`mockOidcUser` 裡面直接給 `testUser`

2023-06-09 07:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
inline

2023-06-09 07:11 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
inline

2023-06-11 13:27 UTC, Wally5077 requested changes
Review done.

2023-06-11 13:27 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/JoinRoomUsecase.kt
> +                .also { presenter.present(it.toJoinedRoomEvent("success"))}
presenter 不用吃一個事件

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        val joinerId = principal.subject ?: throw PlatformException("User id can't be null.")
**User id must exist.**

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +            .thenJoinRoomSuccessfully()
1. 你的變數要按照「測試案例」名稱一致
2. 這檔案「的測試案例」都與留言 1 的規則一致

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        testRoom = giveUserACreatedEncryptedRoomC(testUser, password)
1. `val roomC = giveUserCreatedRoomWithPassword(userA, password)`
2.  測試案例名稱一併改

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        val userB = userRepository.createUser(User(User.Id("2"), "test2@mail.com", "winner1122"))
1. 這可以有個 createUser 的方法做這件事，如下
```kotlin
val userB = createUser("2")
```
2. 這檔案「的測試案例」都與留言 1 的規則一致

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    }
ditto「測試案例」

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun createTestRoom(host : User, password: String? = null): Room = roomRepository.createRoom(
`createRoom`

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        testRoom = giveTheHostCreatedPublicRoom(testUser)
`giveTheHostCreatedRoom`

2023-06-11 13:27 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
>      }
整個檔案的擺放順序：
1. 「測試案例」
2. 打 API 或 Repo save 的 given 方法
3. then 擴充方法

2023-06-15 14:04 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    fun giveUserACreatedRoomCWithPassword_WhenUserBJoinRoomCAndPasswordIsCorrect_ThenShouldSucceed() {
`WhenUserBJoinRoomCWithCorrectPassword`

2023-06-15 14:05 UTC, frankvicky requested changes

2023-06-15 14:05 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
如果沒有要用 Presenter 可以直接回傳，不用實作 Presenter

2023-06-15 14:09 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +                .content(request.toJson())
1. 擴充 AbstractSpringBootTest 的方法
```kotlin
AbstractSpringBootTest.withJson(request: Any) : MockMvcRequestBuilder
        = contentType(APPLICATION_JSON)
            .content(request.toJson())
```
2. 這樣以後其他人就不都需要再度填寫這兩行
```kotlin
withJson(request)
```

2023-06-15 14:10 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
>                  .content(request.toJson())
ditto withJson(request)

2023-06-15 14:17 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +    }
既然這沒有任何實作，那我們可以直接回傳 `ViewModel` 就好了

2023-06-15 14:21 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun giveUserCreatedRoom(host: User): Room = createRoom(host)
```kotlin
    private fun givenTheHostCreatePublicRoom(host: User): Room = testRoom = createRoom(host)
```

2023-06-15 14:24 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +    private fun giveUserCreatedRoomWithPassword(host: User, password: String): Room = createRoom(host, password)
`givenTheHostCreateWithPassword`

2023-06-17 11:35 UTC, Wally5077 requested changes
Review done.

2023-06-17 11:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        return  testRoom
變成一行
```kotlin
return testRoom = createRoom(host)
```

2023-06-17 11:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +
ditto 變成一行

2023-06-17 11:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        this.andExpect(status().isOk)
不需要 this.

2023-06-17 11:35 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/RoomControllerTest.kt
> +        this.andExpect(status().isBadRequest)
ditto this.

2023-06-17 11:35 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/RoomController.kt
> +        return ResponseEntity.ok(JoinRoomViewModel("success"))
這邊沒有 No Content 的 ResponseEntity，就可以直接給 JoinRoomViewModel 作為 Response Body 了
```kotlin
return JoinRoomViewModel("success")
```

2023-06-18 14:19 UTC, Wally5077 approved these changes
LGTM

2023-06-19 13:17 UTC, frankvicky approved these changes
LGTM

2023-06-19 13:17 UTC, merged