feat: GET /user/me
Game-as-a-Service/Lobby-Platform-Service pull request #91
Opened 2023-06-04 04:11 UTC by lohas1107

## Why need this change? / Root cause: 
- As a user, I want to see my profile
## Changes made:
- User related
## Test Scope / Change impact:
- UserController
## Issue
- #77

2023-06-05 08:17 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +@RequestMapping("/users")
Excellent!!!

2023-06-05 08:17 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +        return DefaultOidcUser(emptyList(), idToken)
Cool

2023-06-05 08:20 UTC, Wally5077 requested changes
Review done.

2023-06-05 08:20 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    var testUser = User(User.Id("1"), "user@example.com", "winner5566")
變數放到父類

2023-06-05 08:27 UTC, frankvicky approved these changes
LGTM

2023-06-11 01:35 UTC, lohas1107 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    var testUser = User(User.Id("1"), "user@example.com", "winner5566")
@Wally5077 已放到父類

2023-06-23 14:17 UTC, ricksu978 requested changes

2023-06-23 14:17 UTC, ricksu978 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +        getUserUseCase.execute(User.Id(principal.subject))
這邊要改成 Jwt

2023-06-25 09:20 UTC, ricksu978 approved these changes
LGTM

2023-06-25 10:36 UTC, Wally5077 requested changes
**Review done.**

2023-06-25 10:36 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserMeUseCase.kt
> +            }
```kotlin
val user = userRepository.findByEmail(email)?: notFound(User::class).identifyBy("email", email)
presenter.present(user)
```

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +    protected var mockUser: User = User(
Q：為什麼需要 var？

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    fun givenUserCreated_whenGetUserMe_thenShouldReturnUserInfo() {
**givenUserHasLoggedIn_whenGetUserSelf_thenGetUserSuccessfully**

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +            .whenGetUserMe()
對應測試案例名稱

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +    fun getUserMe(@AuthenticationPrincipal principal: Jwt): GetUserMeViewModel {
**getUser**

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +        val presenter = GetUserMePresenter()
**GetUserPresenter**

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +    private val getUserMeUseCase: GetUserMeUseCase
**GetUserUseCase**

2023-06-25 10:36 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/UserControllerTest.kt
> +    fun givenUserNotCreated_whenGetUserMe_thenUserNotFound() {
**givenUserDoesNotLogIn_whenGetUserSelf_thenUserNotFound**

2023-06-25 11:13 UTC, Wally5077 approved these changes
**LGTM**

2023-06-25 11:16 UTC, merged