Feature/save identity provider id
Game-as-a-Service/Lobby-Platform-Service pull request #99
Opened 2023-06-18 09:35 UTC by lohas1107

## Why need this change? / Root cause: 
- Change to use JWT token
## Changes made:
- Create user when login first time
## Test Scope / Change impact:
- OAuth2Controller
## Issue
- #69

2023-06-18 11:15 UTC, kuoche1712003 commented
現在登入成功的流程應該會走到 [CustomSuccessHandler](https://github.com/Game-as-a-Service/Lobby-Platform-Service/blob/feature/save-identity-provider-id/spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomSuccessHandler.kt#L28)
可能需要把  28 29 行改一下
```kotlin
...
        val identityProviderId = authentication.principal.let { it as OidcUser }.subject
        createUserUseCase.execute(CreateUserUseCase.Request(identityProviderId))
...        
```

2023-06-18 12:54 UTC, ricksu978 commented
When Creating an User
We also need `email` field populated.

The created User should look like this:
```
{
  "id": "{mongoId}",
  "email": "email@rick.su",   // <= email 還是要設置
  "nickname": "{randomNickname}",  // <= 記得給 random Username, 請看 issue 76
  "identities" : [ "google-oauth2|108242752022034936604" ]
}
```
Issue https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/76

2023-06-18 14:35 UTC, frankvicky requested changes

2023-06-18 14:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +        userDAO.existsByIdentitiesIn(mutableListOf(mutableListOf(identityProviderId)))
Q：想知道這裡為什麼需要兩層 List？

2023-06-18 14:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/UserDAO.kt
> +    fun existsByIdentitiesIn(identities: MutableCollection<MutableList<String>>): Boolean
ditto 
Q：想知道這裡為什麼需要兩層 List？

2023-06-18 14:35 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
> +    var identities: List<String> = emptyList()
Q：這裡有特別的理由需要使用 `var` 宣告集合嗎？

2023-06-18 14:40 UTC, Wally5077 requested changes
Review done.

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/OAuth2Controller.kt
> +        this.subject ?: throw PlatformException("JWT subject is null")
`JWT subject should exist.`

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +        userDAO.existsByIdentitiesIn(mutableListOf(mutableListOf(identityProviderId)))
Ｑ：這邊使用一層 List 是不是更為合理？

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/dao/UserDAO.kt
> +    fun existsByIdentitiesIn(identities: MutableCollection<MutableList<String>>): Boolean
Ｑ：如果可以使用一層的 List，那是不是能改成 `varargs` 呢？

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun givenInvalidJwtSubject(): String? = null
Ｑ：會不會給一個確定有值的「空字串」也能做到同樣效果呢？

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +        mockMvc.perform(get("/").with(jwt().jwt { it.subject(this) }))
擴充 `withJwt` 的方法，這樣以後其他人需要測試就會更方便
```kotlin
fun MockMvcRequestBuilder(val jwt: Stirng) = with(jwt().jwt { it.subject(jwt) }))
```

2023-06-18 14:40 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
> +    var identities: List<String> = emptyList()
這不可能可以改，應該為 val

2023-06-18 14:40 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/UserRepository.kt
> +    fun existsByIdentitiesIn(identityProviderId: String): Boolean
```kotlin
fun existsByIdentitiesIn(varargs identityProviderId: String): Boolean
```

2023-06-18 14:48 UTC, kuoche1712003 requested changes
Review done.

2023-06-18 14:48 UTC, kuoche1712003 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            ?.thenShouldLoginFailed()
你這邊 givenInvalidJwtSubject 是 null
下面的 whenUserLogin 和 thenShouldLoginFailed 都不會執行
這應該不是你要的測試情境

2023-06-18 14:56 UTC, kuoche1712003 commented
@Wally5077 @frankvicky 
目前登入成功後的邏輯由 CustomSuccessHandler 負責
其實 OAuth2Controller 目前應該是沒有作用的, 需要連同 Test 整個拔掉嗎？
還是其實可以留下來, 因為不知道怎麼測 CustomSuccessHandler

2023-06-23 09:24 UTC, kuoche1712003 requested changes
Review done.

2023-06-23 09:24 UTC, kuoche1712003 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +        var user = userRepository.findByEmail(request.email)
這個寫法是已經決定用 email 去 group user 了
@ricksu978 上次討論的結果這部分還沒決定吧

2023-06-23 09:24 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomSuccessHandler.kt
> +        val jwt = authentication.principal.let { it as Jwt }
這邊要改回 OidcUser 才會是正常的

2023-06-23 10:38 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomSuccessHandler.kt
> +        val jwt = authentication.principal.let { it as Jwt }
參考之前討論的結論，用不同的 identity provider 但登入的 email 相同會合併在一起，否則這邊就不需要用 list 了吧
<img width="756" alt="Screenshot 2023-06-23 at 18 35 31" src="https://github.com/Game-as-a-Service/Lobby-Platform-Service/assets/5073353/69fc520c-763b-42d9-8617-ea015a931ec1">

2023-06-23 10:43 UTC, kuoche1712003 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomSuccessHandler.kt
> +        val jwt = authentication.principal.let { it as Jwt }
我印象中那時候是想說之後會有帳號綁定的功能
到時候再綁定不同的 identities 然後指定誰是主要的 email
你現在這樣的設計表示之後不同的 email 不能綁定再一起
可能需要 @ricksu978 幫我們釐清一下

2023-06-23 11:45 UTC, ricksu978 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/configs/securities/CustomSuccessHandler.kt
> +        val jwt = authentication.principal.let { it as Jwt }
### 第一階段
- Identity Provider 登入的 email 如果相同會合併在一起，這部分是系統自動合併。

### 目標
- Identity Provider 登入的 email 如果相同依然會合併在一起 (系統自動)
- Identity Provider 的 email 「不同」，也能合併在一起，但合併的步驟不會做在登入，也不會是系統自動合併
  而是需要使用者先登入，然後在帳號頁面某處點擊「連結/新增」其他 Identity Provider，這邊需要前端配合。
- 大平台支援改 email，這部分需要寄 Email 驗證擁有權

### 總結
@lohas1107 做的在第一階段是 Ok 的。

2023-06-23 11:50 UTC, ricksu978 requested changes

2023-06-23 11:50 UTC, ricksu978 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +                user = userRepository.createUser(request.toUser())
這邊可以順手把 https://github.com/Game-as-a-Service/Lobby-Platform-Service/issues/76 做掉嗎?

新增時給 random nickname 即可，感謝。

2023-06-23 12:30 UTC, kuoche1712003 approved these changes
功能部分 ok
code style 交給其他人

2023-06-23 13:18 UTC, ricksu978 approved these changes

2023-06-24 14:51 UTC, Wally5077 requested changes
Review done.

2023-06-24 14:51 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +    }
外部調用 `!hasIdentity` 就好了

2023-06-24 14:51 UTC, Wally5077 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +        User(id, email, nickname, identities + identityProviderId)
是否可以直接將 **identityProviderId** 加進 User 的 identities 即可
而不用再創一個新 User？

2023-06-24 14:51 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
> +            nickname = "user_${UUID.randomUUID()}",
1. static import `randomUUID()`
2. 改用擴充方法，否則 `toUser` 可以到處用

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +            .build()
這兩個方法看起來可以是一個變數

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun givenInvalidJwtSubject_whenUserLogin_thenShouldLoginFailed() {
`whenUserLoginＷithInvalidJwt_thenShouldLoginFailed`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .whenUserLogin()
`whenUserLogin(InvalidJwt)`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .whenUserLogin()
`whenUserLogin(googleOAuth2Jwt)`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun givenOldEmail_andOldIdentityProviderId_whenUserLogin_thenLoginSuccessfully() {
Q：特別強調 Old 的原因是什麼？
`whenUserLoginＷithGoogleOAuth2Jwt_thenLoginSuccessfully`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .whenUserLogin()
`whenUserLogin(discordOAuth2Jwt)`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun givenOldEmail_andNewIdentityProviderId_whenUserLogin_thenSaveNewIdentityProviderId() {
`whenUserLoginWithDiscordOAuth2Jwt_thenUserHaveNewIdentity`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +            .thenSaveNewIdentityProviderId()
`thenUserHaveNewIdentity`

2023-06-24 14:51 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun givenNewEmail_andNewIdentityProviderId_whenUserLogin_thenCreateNewUser() {
`whenUserLoginWithNewIdentity_thenCreateNewUser`

2023-06-24 15:50 UTC, lohas1107 commented on domain/src/main/kotlin/tw/waterballsa/gaas/domain/User.kt
> +        User(id, email, nickname, identities + identityProviderId)
因為 identities 宣告為 val 所以這邊才會再創一個新 User

2023-06-24 15:52 UTC, lohas1107 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +            .build()
mockDefaultUser() 已改為變數
mockJwt() 因為要帶入不同 identity provider 的 Id 而產出不同的 JWT，所以沒有改成變數

2023-06-24 15:54 UTC, lohas1107 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun givenOldEmail_andOldIdentityProviderId_whenUserLogin_thenLoginSuccessfully() {
是為了強調使用者是否曾經登入過，已調整情境描述的命名

2023-06-25 04:19 UTC, Wally5077 requested changes
Review done.

2023-06-25 04:19 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    fun whenUserLoginWithNewIdentity_thenCreateNewUser() {
**whenUserLoginAtTheFirstTime_thenCreateNewUser**

2023-06-25 04:19 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    }
參數用 **vararg identityProviderIds**，這樣可以外面傳多個 identityProviderId
```kotlin
thenWouldHaveIdentityProviderIds(googleIdentityProviderId, discordIdentityProviderId)
```

2023-06-25 04:19 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenCreateNickname(): User {
**thenNickNameShouldBeRandomName**

2023-06-25 04:42 UTC, Wally5077 requested changes
Review done.

2023-06-25 04:42 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
> +    val identities: MutableList<String> = mutableListOf()
default `emptyList()`

2023-06-25 04:42 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +        this.andExpect(status().isBadRequest)
this. 可以拿掉

2023-06-25 04:42 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenSaveIdentityProviderId(identityProviderId: String): User {
**User?.thenWouldHaveIdentityProviderIds**

2023-06-25 04:42 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenNickNameShouldBeRandomName(): User {
**User?.thenNickNameShouldBeRandomName**

2023-06-25 05:56 UTC, Wally5077 requested changes
Review done.

2023-06-25 05:56 UTC, Wally5077 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/CreateUserUseCase.kt
>          }
```kotlin
with (request) {
    when {
       user == null -> createUser()
       !user.hasIdentity(identityProviderId) -> user.addUserIdentity(identityProviderId)
    }
}
```

2023-06-25 05:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/AbstractSpringBootTest.kt
> +    final fun String.toJwt(): Jwt =
protected

2023-06-25 05:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    val invalidJwt = Jwt(
private final

2023-06-25 05:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenNickNameShouldBeRandomName(): User {
裡面也要 `assertThat(this).isNotNull`

2023-06-25 05:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenWouldHaveIdentityProviderIds(vararg identityProviderIds: String): User {
**User?.thenWouldHaveIdentityProviderIds**

2023-06-25 05:56 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun User.thenWouldHaveIdentityProviderIds(vararg identityProviderIds: String): User {
裡面也要 assertThat(this).isNotNull

2023-06-25 07:24 UTC, Wally5077 requested changes
Review done.

2023-06-25 07:24 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/it/controllers/OAuth2ControllerTest.kt
> +    private fun ResultActions.thenUserHaveNewIdentity() {
參數 `vararg identityProviderIds: String` 上，不要方法裡面寫死 `googleIdentityProviderId, discordIdentityProviderId`

2023-06-25 07:42 UTC, Wally5077 approved these changes
**LGTM**

2023-06-25 07:45 UTC, frankvicky approved these changes

2023-06-25 07:49 UTC, merged